name: publish

on:
  push:
    branches:
      - main
    tags:
      - v[1-9]+.[0-9]+.[0-9]+
jobs:
  publish:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://registry.npmjs.org/slack-status-api
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}